package com.meetingops.domain.model;

import com.meetingops.domain.enumeration.DraftActionStatus;
import com.meetingops.domain.enumeration.DraftActionType;

import java.time.Instant;
import java.util.UUID;

/**
 * Domain model representing a draft follow-through action generated by the drafting agent.
 *
 * <p>A DraftAction is a proposed external-system change (task creation,
 * calendar event, or email) generated via MCP tool calls but not yet
 * executed. It must transition through human approval per FR-6.3.</p>
 *
 * @param id               unique identifier
 * @param extractedItemId  the extracted item this action was derived from
 * @param meetingId        the meeting context for this action
 * @param actionType       type of action (TASK, CALENDAR_REMINDER, EMAIL)
 * @param payloadJson      JSON payload representing the action details
 * @param status           current lifecycle status
 * @param originalPayload  immutable original AI-generated payload
 * @param finalPayload     the approved/edited payload (may differ from original)
 * @param promptVersion    version of the prompt/model used for drafting
 * @param createdAt        timestamp of creation
 * @param updatedAt        timestamp of last update
 *
 * @author MeetingOps Team
 * @since 1.0.0
 */
public record DraftAction(
        UUID id,
        UUID extractedItemId,
        UUID meetingId,
        DraftActionType actionType,
        String payloadJson,
        DraftActionStatus status,
        String originalPayload,
        String finalPayload,
        String promptVersion,
        Instant createdAt,
        Instant updatedAt
) {
    /**
     * Creates a new DraftAction with auto-generated UUID and DRAFTED status.
     *
     * @param extractedItemId the extracted item this action was derived from
     * @param meetingId       the meeting context
     * @param actionType      type of action
     * @param payloadJson     JSON payload
     * @param promptVersion   prompt/model version used
     * @return a new DraftAction with DRAFTED status
     */
    public static DraftAction create(final UUID extractedItemId,
                                     final UUID meetingId,
                                     final DraftActionType actionType,
                                     final String payloadJson,
                                     final String promptVersion) {
        return new DraftAction(
                UUID.randomUUID(),
                extractedItemId,
                meetingId,
                actionType,
                payloadJson,
                DraftActionStatus.DRAFTED,
                payloadJson,
                null,
                promptVersion,
                Instant.now(),
                Instant.now()
        );
    }

    /**
     * Returns a copy with updated status and final payload.
     *
     * @param newStatus  the new status
     * @param finalPayload the approved/edited payload
     * @return a new DraftAction with updated fields
     */
    public DraftAction withApproval(final DraftActionStatus newStatus,
                                    final String finalPayload) {
        return new DraftAction(
                this.id, this.extractedItemId, this.meetingId, this.actionType,
                finalPayload, newStatus, this.originalPayload, finalPayload,
                this.promptVersion, this.createdAt, Instant.now()
        );
    }
}
